export const WorkerMessageTypes = Object.freeze({
    CONNECT_WORKER : 'CONNECT_WORKER',
    CONNECT_WORKER_SUCCESS : 'CONNECT_WORKER_SUCCESS',
    CONNECT_WORKER_FAILED : 'CONNECT_WORKER_FAILED',

    SET_WORKER_CONFIG : 'SET_WORKER_CONFIG',
    SET_WORKER_CONFIG_FAILED : 'SET_WORKER_CONFIG_FAILED',
    WORKER_READY : 'WORKER_READY',

    CONNECT_SOCKET : 'CONNECT_SOCKET',
    CONNECT_SOCKET_SUCCESS : 'CONNECT_SOCKET_SUCCESS',
    CONNECT_SOCKET_FAILED : 'CONNECT_SOCKET_FAILED',

    SUBSCRIBE_DATA : 'SUBSCRIBE_DATA',
    SUBSCRIBE_DATA_FAILED : 'SUBSCRIBE_DATA_FAILED'
});


